name: "Reset Branch"
description: "Reset a branch to given branch"
inputs:
  github_token:
    description: "Token to authenticate with GitHub"
    required: true
    default: ${{ github.token }}
  base_branch:
    description: "Branch you want to use as the base to reset too"
    required: true
    default: "main"
  reset_branch:
    description: "Branch you want to reset"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.base_branch }}
    - ${{ inputs.reset_branch }}
    - ${{ inputs.github_token }}
branding:
  icon: "git-merge"
  color: "gray-dark"
